<li class="contacts-info">
    <span class="contacts-name"
          role="link"
          tabindex="0"
          data-mage-init='{"dropdown":{}}'
          data-toggle="dropdown"
          data-trigger-keypress-button="true">
        <span><?=$block->escapeHtml(__('Contacts'))?></span>
        <div type="button"
             class="action switch"
             tabindex="-1"
             data-action="contact-menu-toggle">
            <span><?= $block->escapeHtml(__('Change')) ?></span>
        </div>
    </span>

    <div class="contacts-menu" data-target="dropdown">
        <ul class="header links">
            <li class="link">
                <span class="contact value">Mail: deault@mail.com</span>
            </li>
            <li class="link">
                <span class="contact value">Phone: 123123 1231 12313</span>
            </li>
        </ul>
    </div>
</li>
